### ISSUE TITLE
メッセージ > グループから退会でエラー

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#100]
メッセージ一覧からチャットルームは削除されるので処理自体は完了しているようですが、「サーバーエラー」のアラートが断続的に出続けています（ [x] をタップしても消えない ）
https://www.dropbox.com/s/lszvn3kswfthqdh/RPReplay_Final1556006550.MP4?dl=0

**Comment by inafact** [comment]
ios 1.1 build 1.0 / android 1.1 build 7

似て修正済

必要であれば確認お願いします @thirozumi

**Comment by thirozumi** [comment]
「認証に失敗しました」のアラートが一瞬出たけどサインアウトになりました。

**Comment by thirozumi** [comment]
「認証に失敗しました」のアラートが一瞬出つつ、サインイン画面に遷移しました。

これは自分が退出 => 自分はサインアウト、部屋に「 {Username} が退出しました」のメッセージが出るっていう仕様でしたっけ？前バージョンの名残とかですかね。 @hiroyuki 

何となくサインアウトせず退出した部屋のメッセージが一覧から消えて「退出しました」のスナックバー、みたいなのが良いのかなとも思ったんですが、アーキテクチャ的はいかがでしょうか。

**Comment by inafact** [comment]
@thirozumi 

> これは自分が退出 => 自分はサインアウト、部屋に「 {Username} が退出しました」のメッセージが出るっていう仕様でしたっけ？前バージョンの名残とかですかね。 @hiroyuki

自分がサインアウトはバグかと思います。

このグループチャット退出時の挙動、いくつかのケースが混在してそうなので、reproduceの方法やそもそもの仕様も含めてちょっと整理します..

**Comment by hiroyuki** [comment]
クイストさん含めて確認

**Comment by inafact** [comment]
別系統で再発するようになってしまったので1.3で再度対応

**Comment by inafact** [comment]
リリースしましたのでクローズします。

実機で問題発生するようでしたら次バージョンのマイルストーンで再度オープンしてください
