### ISSUE TITLE
フッタナビ > 緑丸インジケーターの削除タイミング

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#102]
フッタナビゲーションの緑丸のインジケーター、別タブに移ったタイミングで消えるようにお願いします。

![1AD6A11C-4994-408B-B0EA-CEB9C1BCA7CB](https://user-images.githubusercontent.com/493379/56576188-ae322380-6602-11e9-84da-e14f66a47f28.png)

**Comment by inafact** [comment]
merged #50
