### ISSUE TITLE
全体的にロードが重い

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#116]
・画像のローディングアニメーション追加
・画像のサイズをもっと小さくする（サーバー側で対応？）

**Comment by hiroyuki** [comment]
@inafact 都度都度画像をロードしているようなのですが、一度ロードした画像はキャッシュするようになっていますか？

**Comment by hiroyuki** [comment]
@inafact 若干ましになった気がしますが、例えば、コミュニティでトピックをリスト表示において、すでに写真をロード完了し、表示されているトピックの詳細を開くとさいど同じ写真をロードしているように見えるのですが、これは使い回せないのでしょうか？

**Comment by inafact** [comment]
@hiroyuki 

testflightの2.1.xですが、こちらまだ厳密には画像のキャッシュには対応しておらず、それ以外の最適化等を図っているのみです。
今週どこかで、画像キャッシュの適用とその他いくつかのissueに関連に対応したものをtestflight上でリリース予定です。

**Comment by hiroyuki** [comment]
@inafact なるほどです！失礼しました！
よろしくお願い致します。

**Comment by inafact** [comment]
画像を使用するビューの構成を替えた関係で、iOSの（iPhone Xなどの）ノッチがあるデバイスで画像のセーフエリアへのオーバーフローが適用されていない箇所が発生してます。

別途対応中です。

**Comment by hiroyuki** [comment]
最新testFlight確認しましたが、はやくなりましたね！

**Comment by hiroyuki** [comment]
一旦クローズします。
