### ISSUE TITLE
過去のメッセージに遡れない

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#118]
過去のメッセージをみたいと思ってもメッセージウインドウが最新に戻ってします。
（ビデオ参照）
https://photos.app.goo.gl/C62A2zkhRafdqxxd7

**Comment by thirozumi** [comment]
最新のメッセージがあった時に一番下までスクロールさせるイベントが解除できてないかも

**Comment by hiroyuki** [comment]
こちら確認しましたが、まだ起こっているようです。
iOS iPhone X です。
