### ISSUE TITLE
メニューバー右の「✓ アイコン押下」→「決定」のフローが気づかれにくい

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#123]
https://sketch.cloud/s/V0ZVq/a/JrjaAz
https://sketch.cloud/s/V0ZVq/a/Q4QGAG
https://sketch.cloud/s/V0ZVq/a/poZmbA
https://sketch.cloud/s/V0ZVq/a/1mR294
https://sketch.cloud/s/V0ZVq/a/0d5oy0
https://sketch.cloud/s/V0ZVq/a/pok8nR
https://sketch.cloud/s/V0ZVq/a/xe9zOl
https://sketch.cloud/s/V0ZVq/a/4bdM4o

**Comment by hiroyuki** [comment]
@inafact こちら全部変えるのが面倒であれば、右上のままにして、吹き出しのようなもので、入力したらここをクリックしてねといったガイドを付けるというのでもよい気がします。竹田さんとも相談していただき。（なぜか竹田さんにメンションが飛ばせない）

**Comment by thirozumi** [comment]
@hiroyuki メニューバー右上のチェックアイコンが決定ボタンになっているものに関して、「OK」というテキストにすることで明示的にしました。同位置に「キャンセル」もあり、整合性も同時に図っています。

**Comment by hiroyuki** [comment]
@thirozumi ありがとうございます！
一旦こちらで進めましょう。

**Comment by thirozumi** [comment]
@hiroyuki ありがとうございます。一点失礼しました、レジスターの時は最後にOKなので、「次へ」とします。
<img width="1847" alt="Screen Shot 2019-10-04 at 17 51 27" src="https://user-images.githubusercontent.com/493379/66194537-9f7e8b00-e6cf-11e9-8149-cb0c298d66a4.png">

**Comment by inafact** [comment]
@hiroyuki この変更に関してですが、アプリの実装として進めてしまうで大丈夫でしょうか？
（一旦sketchのプレビューで先方に確認もらったほうがいいのか？など）

**Comment by hiroyuki** [comment]
あ、確認とります！

**Comment by inafact** [comment]
こちら特に指摘内容であれば実装進めます

**Comment by hiroyuki** [comment]
@inafact レスないので、このまま進めてくださいませ！
