### ISSUE TITLE
コミュニティの選択をしたら、すぐに一覧画面に戻る

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#124]
https://sketch.cloud/s/V0ZVq/a/0dDvAW/play
ここから
https://sketch.cloud/s/V0ZVq/a/9mradP/play
ここへ直接戻る

<img width="377" alt="Screen Shot 2019-10-04 at 17 57 29" src="https://user-images.githubusercontent.com/493379/66194892-74486b80-e6d0-11e9-87a8-76171fdbf133.png">

**Comment by thirozumi** [comment]
@inafact こちら #132 とマージさせてくださいませ！
