### ISSUE TITLE
DONE表記を「送信」もしくはデザインにあるような送信アイコンに変更

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#125]
メッセージ画面

<img src='https://user-images.githubusercontent.com/493379/63678226-b8229800-c829-11e9-8ca8-af183823ce89.PNG' width='375px'>

**Comment by thirozumi** [comment]
デザイン上はそうなっているので反映漏れかもです。
https://sketch.cloud/s/V0ZVq/a/8O3Djw

<img src='https://user-images.githubusercontent.com/493379/63676568-2feec380-c826-11e9-984d-1b317cff4fb0.png' style='max-width:375px;height:auto;'>

**Comment by inafact** [comment]
@hiroyuki @thirozumi こちら、正しくはiOSのキーボードオプションの指定をどうするかの問題です（現状文字を入れると送信アイコンは表示されるはず）。

ライブラリの仕様でキーボードにカスタムのツールバーを設定できるようになっているのですが、それのデフォルト値が「DONE」になっています。

対処としてはツールバー自体を非表示にする方向で進めようと思っていますが、一応他の手としては文言を変えることも可能です。
ツールバーを表示するメリットとしては、iOSには（Androidにはキーボードに閉じるボタンがある。ただしメッセージのビューでは現状キーボードのエリア外をタップでいずれのOSでも閉じるようにはしてある）キーボードを閉じるボタンがないので、それの役割を現状「DONE」に与えている感じです。

**Comment by thirozumi** [comment]
なるほど、ありがとうございます。メッセージ画面のタップで引っ込むので、僕はツールバー不要ではと思いました。

**Comment by hiroyuki** [comment]
@inafact 表示しないで良いと思います！
