### ISSUE TITLE
「できる」「ほしい」のラベルを見やすく

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#126]
・もっと大きく
・色を変えたい

**Comment by thirozumi** [comment]
@hiroyuki サイズを上げ、「できる」と「ほしい」で色を反転させてみました。
https://sketch.cloud/s/V0ZVq/a/EYOJyo

**Comment by hiroyuki** [comment]
@thirozumi ラベル自体をもう一盛り大きくできないでしょうか？

**Comment by thirozumi** [comment]
@hiroyuki してみました、これより大きいと 320px幅の端末でちょっと存在感出過ぎちゃうので、できればこのくらいに収めたいですね。

<img width="403" alt="Screen Shot 2019-10-04 at 18 10 29" src="https://user-images.githubusercontent.com/493379/66195862-81fef080-e6d2-11e9-8db6-d513b14defc7.png">

**Comment by hiroyuki** [comment]
@thirozumi ありがとうございます。
一旦こちらでクライアントにも確認しますね！

**Comment by hiroyuki** [comment]
@thirozumi こちらでOKです。進めてくださいませ！

**Comment by thirozumi** [comment]
@inafact デザインデータに反映して別途 PR 出しました
https://github.com/h4us/commons-people-design/pull/26

**Comment by inafact** [comment]
@thirozumi 

ちなみに詳細のビューの時はデザイン変わらずでしょうか？

**Comment by thirozumi** [comment]
@inafact こっちですよね、僕はそのままで大丈夫と思います。

![MyTopic](https://user-images.githubusercontent.com/493379/66371306-c8f42b00-e9dd-11e9-9de1-90d23a6f19a2.png)

**Comment by hiroyuki** [comment]
僕もそのままでいいと思います！

**Comment by hiroyuki** [comment]
テストフライト確認しました。
@thirozumi 問題なければcloseしてOKです！

**Comment by thirozumi** [comment]
クローズします！
