### ISSUE TITLE
メッセージ画面で、アイコン＋名前をクリックしたらプロフィールに飛べるようにする。

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#128]

**Comment by inafact** [comment]
@hiroyuki  @thirozumi 

ちょっと本issueからは逸れる話なのですが、現状、トピック（Ad）に対するポイントの支払いというのが、このビュー（自分以外のユーザーのプロフィール表示）→「ポイントを送る」ボタンでポイント送信画面に遷移した際に適用される実装になっています。

メッセージスレッドからの遷移に対しては参照元のトピックIDが無いことになるので、単に実装上そこで分岐すれば済む話なのですが、画面上のフローが途中から同じなので、トピックに対して支払う場合は何かUI上区別があったほうがよいのでは？とちょっと思ったのですが、いかがでしょうか？

**Comment by hiroyuki** [comment]
@inafact それは、このビューからアイコン名をクリックして遷移した場合、このトピックIDに紐づいたビューに戻ってこれないということですか？
例えば、トピック詳細画面でアイコンクリックすると、モーダルが下から上がってきますが、これと同じ仕組みにしたとしても同様ということでしょうか？

**Comment by inafact** [comment]
@hiroyuki いえ、それは大丈夫です。

特に気ならないようであれば、単にデータ構造上の対応をすればよいだけなので、問題なく対応できると思います。

どちらかというと、トピックに対してポイントを支払う際に、このユーザープロフィールのモーダルを開いてからポイント支払い画面に遷移するので、同じ様な遷移が別のところでもあると「トピックに対して支払った」感が薄くなるかな..とちょっと感じただけですね。

**Comment by hiroyuki** [comment]
@inafact あ、なるほど。
モーダル上からの支払いボタンをdisableした方が良いんじゃないかということですかね。
たしかに、それはありそう。

**Comment by hiroyuki** [comment]
@inafact 確認しました。問題なさそうなのでよければクローズお願いします。
