### ISSUE TITLE
メッセージ・コミュニティの通知がどこの通知かわからない。

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#129]
![5A8E62C4-C0B3-4961-8262-EC7AA861BF12](https://user-images.githubusercontent.com/109019/64154438-da409980-ce6b-11e9-854a-88063c1995c9.png)

**Comment by thirozumi** [comment]
@hiroyuki こちらどういう意味でしょうか？

**Comment by hiroyuki** [comment]
@thirozumi ノーティファイされているのが、どのコミュニティのどのメッセージなのか、アテンションがないので、わからないなという意味でした。

**Comment by thirozumi** [comment]
@hiroyuki なるほどです。とすると、タブバー側にもインジケーター表記が必要ですかね。APIは足りているのでしょうか？
![Home](https://user-images.githubusercontent.com/493379/66196348-516b8680-e6d3-11e9-9881-caa683de8934.png)

**Comment by hiroyuki** [comment]
API確認します！

**Comment by hiroyuki** [comment]
@inafact こちらAPI仕様確認しましたが、別で話にあったどこまでクライアントでやるかという議論にかかわってますね。一度稲福さんのほうで、改善するにあたって、サーバー／クライアント側の提案いただけますでしょうか？

**Comment by inafact** [comment]
@hiroyuki @thirozumi 
現状APIの実装の範囲内でですが、竹田さんが提案されているコミュニティのタブに対してインジケーター表示させるところはクライアント側で対応可能です。

> どのコミュニティのどのメッセージなのか、アテンションがないので、わからないなという意味でした。

ということですが、これはスレッドのプレビューリストのところにも何らかのアラートを出したい、ということですかね？ @thirozumi デザイン的にどうでしょうか？

**Comment by hiroyuki** [comment]
@inafact @thirozumi はい、どのメッセージ板が新着なのかというのを、例えば該当のものは太字で表示するなど、できたらいいなと思いました。

**Comment by thirozumi** [comment]
太字はカレントのコミュニティの意味に見えちゃうので、デザイン通りの緑丸がよいかなと。

**Comment by hiroyuki** [comment]
@thirozumi あ、コミュニティ名の話ではなくて、メッセージの頭だけ見えている部分です。

**Comment by hiroyuki** [comment]
現状、コミュニティ名まではインジケータがついてますが、どのメッセージかわからないというのを解決したいなと。

**Comment by thirozumi** [comment]
@hiroyuki なるほどです。太字 or 色だとちょい視認性低いかなと思ったのでインジケータをアイコン側にもつける方向で調整してみましたが、どうでしょうか。
https://sketch.cloud/s/V0ZVq/a/e4vgnq

![Home](https://user-images.githubusercontent.com/493379/66361914-a3eec080-e9bb-11e9-8b76-d686e1fb45d0.png)

**Comment by hiroyuki** [comment]
@thirozumi ありがとうございます。ちょっと写真に被っているところが、見辛い気もします。もう少し離してしまうか、それか別の場所ってのはないですかね？

**Comment by thirozumi** [comment]
@hiroyuki たしかに写真によって視認性がブレそうですね。外側に 2px ほど白地を入れて被りを逃がしてみました。
https://sketch.cloud/s/V0ZVq/a/e4vgnq
![Home](https://user-images.githubusercontent.com/493379/66362705-bdddd280-e9be-11e9-9491-dd7a069970f0.png)

**Comment by hiroyuki** [comment]
@thirozumi 良いと思います。こちらクライアントからのツッコミではないので、このまま進めてOKです！

**Comment by thirozumi** [comment]
@inafact データ後ほどパスしますので、よろしくです。

**Comment by hiroyuki** [comment]
@inafact これってサーバー側の仕組みのアップデートがないと対応できないってことですよね？

**Comment by inafact** [comment]
@hiroyuki 

厳密にどういう挙動を想定しているかにもよるんですが、インジケータの表示自体は現在のAPIでもできます。

新規のメッセージが来た際と、未読のスレッドをチェックした後のリフレッシュ？的な動作として、現状だと再度１ページ目からスレッド一覧を取得してきてUIの内容を入れ替える or マージしていく、みたいなことが必要なのですが、個別のスレッドに対して未読かどうかをチェックする方法がないので、このあたりが若干ややこしい＆これでいいのだろうか..？みたいなことになっているんですが..。

ちょっと文章では説明しにくいので、一度testflightにアップロードして確認してもらったほうが良さそうかなと。もうしばしお待ちください..

**Comment by hiroyuki** [comment]
@inafact 確認しましたが、バグなのか、うまく動いてないかもしれないです。
やはりサーバー側で対応した方が良いですかね？

![D1447E68-9084-4AB0-A110-E8921B1BF5BE](https://user-images.githubusercontent.com/109019/68654208-c783c880-0570-11ea-8059-deadc305c56f.png)

**Comment by inafact** [comment]
@hiroyuki 

こちら状況の確認なのですが、新規にメッセージのやり取りがあってもリストビュー内のインジケータが更新されない、という状態でしょうか？
現状の実装としては、未読メッセージ板件数取得のAPIを定期的に呼び出し、取得されたデータの未読件数に変更があった場合、リストビューのリフレッシュが行われるようになっています。
こちらの把握としては、上記の実装方法の関係で若干タイムラグがある、というのがまずひとつ。
もうひとつ、未読メッセージ板件数取得のAPIから返される数が0でなくても、実際にメッセージ板検索APIから取得できるメッセージスレッドのリスト（データの各エントリにunreadフラグがあって、リストビューのインジケータ表示・非表示に関してはこちらを参照しています）は全て既読であるというケースがあるようです。

こちらはもしかすると、以前あったような自動応答のメッセージが検索結果に該当したなかったりであるとか、サーバーサイドにおける数え方などの問題かもしれませんので、その点はクイストさんに確認してみます。

**Comment by hiroyuki** [comment]
えと、「加賀」に通知がついてますが、どのメッセージなのかわからず。
ただしくは、少なくとも一つのメッセージに●がついていないといけないですよね？

**Comment by inafact** [comment]
@hiroyuki 

こちら、クイストさんにサーバー上の不具合対応していだきました。
僕の確認した限りでは意図した動作になっていると思うのですが、いかがでしょうか？

**Comment by hiroyuki** [comment]
@inafact  なんかよさそうです！確かに、おっしゃる通り多少のラグなどはありますが、いったんこちらで様子見ますかね。
