### ISSUE TITLE
QR決済後に支払いましたビューが欲しい

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#130]
現在はメッセージだけ表示されるが、それだと店舗側が支払い確認をする際に確認しずらいかと思いました。なので、支払い完了！のビューが欲しい。

**Comment by thirozumi** [comment]
@hiroyuki 画面起こしました、一度ご確認ください。https://sketch.cloud/s/V0ZVq/a/ZRPKop

**Comment by hiroyuki** [comment]
@thirozumi 良いと思います！
