### ISSUE TITLE
コミュニティの選択画面で「選択する」を押下したら一覧にもどる

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#132]
選択中かどうかのステータスは一覧でも確認ができるので、以下「選択中」のビューは不要です。
<img width="377" alt="Screen Shot 2019-10-04 at 17 57 29" src="https://user-images.githubusercontent.com/493379/66194892-74486b80-e6d0-11e9-87a8-76171fdbf133.png">

**Comment by inafact** [comment]
@thirozumi これって #124 と同じですかね？

**Comment by thirozumi** [comment]
あ、そですね！
