### ISSUE TITLE
iOSでのメッセージ詳細ビュー対応

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#24]
@inafact 現状、以下のようになっていると思うんですが、

```
1. メッセージ入力
2. 送信
3. メッセージ一覧に追加
```

- [x] メッセージ一覧に追加する際、ボックス内の入力テキストを消去するようにお願いします。
- [ ] メッセージ一覧ボックスの位置を下付き（？）にするなど、送信後に最新のメッセージが見えるようにお願いします。

あと、

- [x] メッセージのテキスト色は `Aa` とあるプレースホルダー用に入れたものなので、入力されたテキストは他と同じ `#333` にお願いします。

https://www.dropbox.com/s/8atxeojj0w254jl/RPReplay_Final1554169392.mp4?dl=0

**Comment by inafact** [comment]
@thirozumi @hiroyuki 

>  メッセージ一覧ボックスの位置を下付き（？）にするなど、送信後に最新のメッセージが見えるようにお願いします。

これ以外にに関しては対応済っぽいので、この内容だけ切り出して1.3に追加します。
この対応、結構UIのパーツを組み直さなければいけないので（内容的にクリティカルであることは承知していますが）、少し時間を要するかもしれません。

場合によっては1.3のリリーススケジュール調整するかもです。
