### ISSUE TITLE
起動時にサーバーエラーのアラートが出現する

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#37]
タイミングなのかもですが、毎回発生するのであれば例外的に出さないようにするなどした方がユーザー迷わないと思います。

![IMG_8528](https://user-images.githubusercontent.com/493379/55700017-95255200-5a08-11e9-9b66-c7705809765a.PNG)

**Comment by inafact** [comment]
@thirozumi 

こちら実際にハンドリングするべきエラーである場合もあるので微妙な部分もあるのですが、このissueで主に起きているのは定期的に未読や新規の投稿を取得しているタスクが、デバイスのネットワークオフライン、サスペンド／レジュームに対して停止・再開をうまく行えてなかったからと思われます。

この辺りのハンドリングを

https://github.com/h4us/commons-people-app/commit/2c9a03b99dfcbfa68e0be408602262b4506aa9c2

追加してあるので、まだ再現するか一度ご確認ください。

**Comment by thirozumi** [comment]
ありがとうございました。起動時の再現はなくなったのでこちらはクローズします。
