### ISSUE TITLE
「メッセージする」押下後にテキストボックスにフォーカスがあたってほしい

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#53]
ローダーが出たままアクションがなくエラーに見えるので、検索の箇所と同じ挙動（検索窓をタップ => テキストボックスにフォーカス）に揃えていただければです。
https://www.dropbox.com/s/pvrpf5e9mvhkodi/RPReplay_Final1555316666.MP4?dl=0

関連:  #24

**Comment by inafact** [comment]
@thirozumi 

https://github.com/h4us/commons-people-app/commit/2c9a03b99dfcbfa68e0be408602262b4506aa9c2

で指摘の箇所については解決しているかと。
メッセージのビューの改善点自体はまだあるとは思うのでそちらは適宜

**Comment by thirozumi** [comment]
ありがとうございました。
