### ISSUE TITLE
コミュニティ投稿からのダイレクトメッセージ

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#56]
コミュニティ投稿から、投稿者へのダイレクトメッセージが送れないようです。
また、その時のメッセージ板の名前は投稿名がいいかなと思いますが、いかがでしょう

**Comment by inafact** [comment]
@hiroyuki 

https://github.com/h4us/commons-people-app/commit/bbce97da63c9527896c310fe6681b1f4aa9db163

でリリース時に対応済という認識です。
問題ありましたら再度オープンしてください。
