### ISSUE TITLE
プッシュ通知の導入

### ISSUE THREAD

**Issue by inafact** [h4us/commons-people-app#6]

**Comment by hiroyuki** [comment]
こちらのプッシュ通知の件、今週中には難しいですかね？

**Comment by inafact** [comment]
@hiroyuki 

一応手元のブランチで作業進めてはいて、

https://github.com/h4us/commons-people-app/projects/2

優先順位的にも高めで考えています。基本的にはアドオン的なもの導入+α程度なのですが、動作テストがややこしく..微妙に完了できていません。

今週中に何とか対応します。

**Comment by hiroyuki** [comment]
@inafact ありがとうございます。
かしこまりました！助かります！

**Comment by inafact** [comment]
Firebaseの導入自体は済。
細かい内容については個別にということでクローズ
