### ISSUE TITLE
メッセージからの送金

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#61]
メッセージからの送金する場合、ダイレクトメッセージであれば直接、送金画面へ。
グループチャットの場合は、参加している人一覧から選択し、送金画面へ。
というのは可能でしょうか。

**Comment by inafact** [comment]
@hiroyuki 

実装的には #73 と重複。

ios 1.1 build 1.0 / android 1.1 build 7

で基本動作については対応済みです。
問題あれば再度オープンしてください。
