### ISSUE TITLE
ポイント送信後のフィードバックメッセージ追加

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#64]
メッセージ画面からポイントを送信後、特に何もなくメッセージ画面に戻るので、デフォルト色のスナックバーで「ポイントを送信しました」と表示できると良いと思います。

<img src='https://user-images.githubusercontent.com/493379/56266903-4ffbd100-6128-11e9-8d27-5be13b56478c.PNG' width='300'>

**Comment by inafact** [comment]
@thirozumi 

こちら、どうも未実装なのではなくて、メッセージのビューがモーダルウィンドウか、ナビゲーションをhiddenにしている状態の時に、スナックバーの親コンテナがアクティブになっていない or 隠されてしまっているようです。対応します。

**Comment by inafact** [comment]
現状実装を要確認

**Comment by inafact** [comment]
@thirozumi 

前バージョンリリース時に対応してあったので閉じます。
本番環境で問題出るようであれば再度オープンしてください。
