### ISSUE TITLE
ポイント一覧の送金ボタンがリスト最下部に被っている

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#65]
プロトタイプでは、リスト最下部の下にボタン分の余白を取って被らないようにしています。
https://sketch.cloud/s/V0ZVq/v8dPYE3/play

<img src='https://user-images.githubusercontent.com/493379/56281620-0f13b480-6148-11e9-9665-61f976a9379c.PNG' width='300'>

**Comment by inafact** [comment]
@thirozumi 

ちなみにAPI経由のページングが追加されたもの（詳しくはクイストさんの仕様書を見ていただけると）に関しては、「さらに読む」ボタンが適宜付加される、ということでよいでしょうか。
ポイント一覧も対象になります。

**Comment by thirozumi** [comment]
> 「さらに読む」ボタンが適宜付加される、ということでよいでしょうか。

@inafact そうですね、ビューに反映しておきました。
https://sketch.cloud/s/V0ZVq/PGj1O1P

**Comment by inafact** [comment]
@thirozumi 

ios 1.1 build 1.0 / android 1.1 build 7

で修正済みです。
実機等で問題が出るようであれば再度オープンしてください
