### ISSUE TITLE
ポイント一覧の数字が大きくなった時のビュー

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#71]
@hiroyuki どのくらいまでフォローする必要があるか謎なのですが、所持ポイントの数値が大きくなった時のビューを考えてみました。

<strike>
@inafact iPhone X/8 の 375px 幅でビューを作ってますが、SE とかの 320px幅ではフォントサイズを下げるとかで大体近い感じにできると嬉しいです。

1行: Helvetica (Roboto) Light / 60px 相当
https://sketch.cloud/s/V0ZVq/PGj1O1P

2行: Helvetica (Roboto) Regular / 40px 相当
https://sketch.cloud/s/V0ZVq/g0K181a

3行: Helvetica (Roboto) Medium / 24px 相当
https://sketch.cloud/s/V0ZVq/8ynVEV3
</strike>

**Comment by hiroyuki** [comment]
@inafact こちらAPIから取得するデータ型って、stringでしたっけ？
Intであれば、最大値4byteだと思うので、
2,147,483,648
が最大だと思います。
@thirozumi

**Comment by thirozumi** [comment]
@hiroyuki ありがとうございます！
@inafact 複数パターン不要にできそうなので、#68 に移行します。
