### ISSUE TITLE
ポイントを送るのユーザー検索

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#73]

**Comment by hiroyuki** [comment]
ポイントを送る際に、加賀からきたら、加賀の人のみ検索、遠野から来たら遠野のみ検索にしたいが、今、全コミュニティのユーザーが表示される

**Comment by thirozumi** [comment]
グループチャット内で送る場合もフィルタされてた方が良いですかね、機能的にはアドオンでいいと思いつつ。
僕 (thirozumi) から送れるのは inafuku, inafact なので、その2名が表示されてるのが自然な気がしますが、どうでしょう？

<img src='https://user-images.githubusercontent.com/493379/56400038-923e2300-628c-11e9-8998-8dcbbae79c81.PNG' width='300'>

**Comment by hiroyuki** [comment]
あ、ここで僕が気にしてるのは、添付の画面で、自分が所属しているコミュニティ以外のユーザーが見えてしまっているところです。
![940CEB28-4E2A-4162-8B93-C79A1B290EEE](https://user-images.githubusercontent.com/109019/56400207-81da7800-628d-11e9-9570-7c7b8d6bf843.png)

**Comment by thirozumi** [comment]
そうですね、ややこしくてすみません。それができるのであれば、グループメッセージの時にさらに絞れると良さそうかなという意見でした。こちらの対応状況に応じてで大丈夫です。

**Comment by inafact** [comment]
@hiroyuki @thirozumi 

ios 1.1 build 1.0 / android 1.1 build 7

で基本動作については実装済みです
問題あれば再度オープンしてください
