### ISSUE TITLE
Kagaコインの送金ができない

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#74]
加賀コインを送ろうとするとサーバーエラー

**Comment by hiroyuki** [comment]
![8F7FAE61-7FDD-4E35-814A-D7143D95AC73](https://user-images.githubusercontent.com/109019/56399372-83557180-6288-11e9-8ec3-4c95e7715e99.png)

**Comment by inafact** [comment]
サーバー側で

```
commonsos.exception.ServerErrorException: community admin is not allowed to send token.
```

エラーが出ています。
以前話されていたethereum側の設定でしょうか？

**Comment by hiroyuki** [comment]
それっぽいですね
きいてみます。

**Comment by hiroyuki** [comment]
@inafact そもそも加賀コミュニティに参加している人が検索できないようなので、再現ができなくなっているようです。 #86 
こちらまずは見てもらった後に聞いてみるしかないかもしれません。

**Comment by hiroyuki** [comment]
問題なさそうなので、クローズします！
ありがとうございました！
