### ISSUE TITLE
相手の入ってないコミュニティのコインが送金リストに表示される

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#75]
送金する際に指定できるコインは、自分が入っていて、かつ、相手が入っているコミュニティのみに限定する
![755509DD-02F0-4D29-B095-C54CA108574D](https://user-images.githubusercontent.com/109019/56399418-cb749400-6288-11e9-9629-497037220bf4.png)

**Comment by inafact** [comment]
こちら、実装していて気づいたのですが、現状コミュニティ管理者以外だと相手のユーザーが参加しているコミュニティ一覧を取得することができませんでした。

設計上の都合もあるのかもしれませんが、クイストさんにリクエストしてみます。
