### ISSUE TITLE
Adminからの送金が重複している

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#76]
Adminアカウントから送金した時に、一回しか送金していないのに、複数回送金されている。
サーバー側の問題の可能性もあるので、切り分けから。
![3D160F90-E48B-438B-9936-8F7B787784CC](https://user-images.githubusercontent.com/109019/56399459-07a7f480-6289-11e9-8690-62419c3e5ddf.png)

**Comment by hiroyuki** [comment]
ログを見た感じ/transactionが重複してコールされている感はあります。
![image](https://user-images.githubusercontent.com/109019/56405060-4ba8f280-62a5-11e9-922c-cc742cdc070e.png)

**Comment by inafact** [comment]
アプリ側でコールバックを複数回登録してしまっている箇所を確認しましたので対応します。

**Comment by hiroyuki** [comment]
問題なさそうです。
OKであれば、クローズしてください！
