### ISSUE TITLE
ウォレットの画面で、タイトルの文字が切れてる

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#77]
Galaxy S7 edge
Android 8.0.0
にて、発生模様
![3ECE563D-1F3C-499E-82C7-62A1547BE86D](https://user-images.githubusercontent.com/109019/56399625-383c5e00-628a-11e9-8996-8264d74c5783.jpeg)

**Comment by inafact** [comment]
@hiroyuki 

こちらも最初のリリース時にエミュレーター上では修正確認済みです。

実機にて問題ある場合は再度オープンしてください。
