### ISSUE TITLE
Androidのアプリアイコンがおかしい

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#78]
背景が透過している模様。
![0D0B47AB-DCAF-44D5-BB1D-C11C1CB3F31B](https://user-images.githubusercontent.com/109019/56399655-6d48b080-628a-11e9-9236-7dc5b7e58b1b.jpeg)

**Comment by thirozumi** [comment]
これ僕かなと思ったんですが、データ上は白地入ってますね。

**Comment by hiroyuki** [comment]
なるほど、なんでだろう。
とりあえず、様子見ですかね

**Comment by inafact** [comment]
@thirozumi @hiroyuki  

sektch上のアセットが、iOS / Androidともにinvalidになってちゃったてので、適宜こちらで生成し直してました。Andoridのアイコン生成時に余計なとこまで透過にしてしまってたようです。

Andoridが（Android Oneなど）OSの上のレイヤ―によってこの辺の仕様が微妙にカスタマイズされるぽいので仕様確認してフォローする基本フォーマットを精査してみます。

**Comment by thirozumi** [comment]
ありがとうございます！

**Comment by inafact** [comment]
@hiroyuki ちなみにこちら、端末もしくはエミュレーターのパッケージは何になりますか？

**Comment by hiroyuki** [comment]
Galaxy S7 edge 
Android 8.0.0

となります！

**Comment by inafact** [comment]
@thirozumi 

こちらのissue、基本的にはアプリのビルド時に解決できるはずですが、根本的な問題として、単に透過をやめればOKということではなくランチャーアイコン、その他（通知の際に使用されるものなど）アイコンの類を

https://developer.android.com/guide/practices/ui_guidelines/icon_design?hl=ja

に沿ったものでデザイン、作成しておく必要があるかも、という認識です。

Galaxy S7 edgeで表示がおかしくなる直接の原因に関しては完全に追えておらず、おそらくsamsungのベンダーテーマが適用されている関係だと思いますので、少なくとも上記のガイドラインに沿ったものが用意できていれば問題にはならないべき..という。

こちらで、ひとまずの解決策は引き続き調査中ですが、お手すきの際に確認いただけると。

**Comment by thirozumi** [comment]
@inafact こちらのテンプレートを使って h4us/commons-people-design/pull/15 でプルリク出しました！
http://designersstash.com/appicontemplate/

**Comment by inafact** [comment]
@thirozumi ありがとうございます。試してみます！

**Comment by inafact** [comment]
@hiroyuki @thirozumi  

こちらもエミュレーターでの動作は確認済みです。

一応補足として、

・Android 8.0（API レベル 26）以上、未満で動作が異なる
・逆に8.0以上の場合（ このイシューで挙がっているGalaxy S7 edgeのケースなど）アダプティブアイコンのガイドに沿っていればある程度カスタムできる

という感じです。
