### ISSUE TITLE
コミュニティ切り替えボタンの表示内容・機能改善

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#79]
参加しているコミュニティが１つしかない場合は、切り替えボタンを非表示にする

**Comment by inafact** [comment]
@thirozumi 一応デザインチェックお願いします！

**Comment by thirozumi** [comment]
@inafact シンプルにアイコンをトリでよいと思いますー
https://sketch.cloud/s/V0ZVq/ygDMD2o/play

<img src='https://user-images.githubusercontent.com/493379/56402846-f6b3af00-6299-11e9-9820-bda4ee307227.png' width='300'>

**Comment by inafact** [comment]
@thirozumi これだと、新しくコミュニティに入れなくないですか？

ていう意味でいうと、ないとまずいのでは、という気も？ @hiroyuki

**Comment by hiroyuki** [comment]
@thirozumi あ、たしかに、、、
ということは、必要ですね、、

**Comment by thirozumi** [comment]
@inafact なるほど、そうですね。。
ではアイコンを「+」にしてタップで SelectCommunity/List を呼ぶなどでは？
https://sketch.cloud/s/V0ZVq/ygDMD2o/play

**Comment by inafact** [comment]
@thirozumi @hiroyuki 

> ではアイコンを「+」にしてタップで SelectCommunity/List を呼ぶなどでは？

了解です。こちらで調整します。

**Comment by inafact** [comment]
こちらも対応済みかと思います。
何かあれば再度オープンしてください。
