### ISSUE TITLE
新規お知らせを公開したが、未読バッジがつかない？

### ISSUE THREAD

**Issue by yumataesu** [h4us/commons-people-app#83]
まず、新規に登録すると、未読バッジが添付画像の赤□のどちらかにつく認識だったのですが、
それであっていますでしょうか？
![Screenshot_20190419-142152](https://user-images.githubusercontent.com/10915510/56408720-bb70aa80-62b0-11e9-9c99-b645571521bd.png)

画像の遠野事務局です！（更新バッジテスト）はID171でwordpress側に保存されていまして、

また、アプリサーバー側で遠野に登録されている更新日時では、
ID171が保存されているのを確認できており、もしかしたらアプリ側なのではと思いissueに挙げさせていただきました。
https://news.test.commonspeople.love/check-api.php

必要であれば、wordpressのアイパスを共有いたしますので、メールアドレスを教えていただけたらと思います。
https://docs.google.com/document/d/1Dzk-iD3ER_YzJDiRbKvPtIDLN0xuhTzHGV3rAZKERjo/edit?usp=sharing
（現在は私と堀さんしか閲覧できない）

よろしくお願いいたします。

**Comment by inafact** [comment]
@yumataesu 

こちら対応中です。すみません！

#50 で詳細追記してマージさせていただきます。
