### ISSUE TITLE
Account:HorristicKagaが検索できない

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#86]
加賀コミュニティに所属しているはず。
![DE81496E-CD2D-4C01-A35E-F6E644EF21F0](https://user-images.githubusercontent.com/109019/56449721-891a8800-6358-11e9-9c50-0469cf7402ec.png)

**Comment by inafact** [comment]
@hiroyuki 

こちら、アプリ側も確認はしてみますが、クエリ自体は送っているはずです。
サーバー側がcapital case等を厳密に区別しているのではないかと。

**Comment by hiroyuki** [comment]
@inafact そうおもってみたのですが、capital変更しても検索にでてこず。
また、capitalは判別しないようにサーバー側はしてもらっていると記憶しています。

**Comment by inafact** [comment]
@hiroyuki お、なるほど..見てみます

**Comment by inafact** [comment]
@hiroyuki 

こちら、アプリ側でAPIからの生のレスポンスをダンプして確認してみたのですが、リクエスト自体は"Ho"で検索するとそのとおりに飛んでいるものの、結果はcapital caseを除いたものしか返ってきていないように見えます。
試しに自分もテストのアカウントを大文字含むものに変えてみたのですが、そちらは問題なかったです。
というか"tic"で検索しても"horristic"しか返ってきませんね..?

**Comment by inafact** [comment]
指摘の通りこちらも必須になったcommunityIdの指定が正しくできてませんでした。

次のビルドで対応します。

お騒がせしました..

**Comment by hiroyuki** [comment]
確認しました！
