### ISSUE TITLE
ウォレットのページから「といあわせ」でエラー

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#87]
![9C222512-6913-4BB1-B88F-AADE427352D3](https://user-images.githubusercontent.com/109019/56449786-35f50500-6359-11e9-8a8f-20eef05788fb.png)

**Comment by inafact** [comment]
@hiroyuki 

こちら、APIの変更で１対１のダイレクトメッセージの際にもCommunity ID の指定が必須になっていたのが原因でした。

次回ビルドで対応します。

**Comment by hiroyuki** [comment]
確認できました！
ありがとうございます。
