### ISSUE TITLE
ログアウトしているのにノーティフィケーション

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#88]
アカウントの削除済みでログアウトしているのにノーティフィケーションが飛んできます

**Comment by hiroyuki** [comment]
別のアカウントでログインしても、前のアカウントのログインが飛んできたりしているようです。

**Comment by inafact** [comment]
@hiroyuki 

サーバー側で登録したデバイスのトークンを削除してしまうのが仕組み的には早いのかなと思っていますが、今までのアプリ・サーバーでの組合せで問題になってないのであればアプリ側で管理することになるんですかね..
一応調査してみます。

**Comment by hiroyuki** [comment]
まぁ、複数アカウントを作る人は、運営側だとおもうので、優先度は特に高くないと思います。

**Comment by hiroyuki** [comment]
クイストさんと確認
