### ISSUE TITLE
メッセージの送信元が誰からかわからない

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#89]
メッセージのアイコンがロードが遅かったり、アイコン画像がそもそも登録されてないと、誰からのメッセージかわからないということが発生してます。

**Comment by thirozumi** [comment]
@hiroyuki 確認しました。

基本路線としては 1 on 1 の場合はアイコンのみ（アイコン設定のないユーザの場合は no image アイコンになる）で、複数人のメッセージのが場合はアイコン+ユーザーネームという感じかなと思っていたのですが、
```
A. 1 on 1 の場合はメニュータイトルが相手のユーザーネームになる
B. トピックからのメッセージの場合はトピック名になる
C. 複数人の場合はグループチャット名のある／なしがある
```
上記の B のケースがありえるので、A 以外はアイコン+ユーザーネームというのが現実的なのかなと。
https://sketch.cloud/s/V0ZVq/Gm353e8

どうでしょうか？

**Comment by hiroyuki** [comment]
確認しました！ありがとうございます。
その路線で良いかと思います。
あと、各メッセージの下か、上に送信日時もあると便利かなと思ったのですが、盛り込みすぎですかね。

**Comment by thirozumi** [comment]
@hiroyuki 
> あと、各メッセージの下か、上に送信日時もあると便利かなと思ったのですが、盛り込みすぎですかね。

ひとまず画面とドラフト仕様を作りました。
https://sketch.cloud/s/V0ZVq/Gm353e8

- メッセージ横のタイムスタンプは `hh:mm`
- 日付が変わった最初のメッセージ上に日付を区切るタイムスタンプが入る
- 日付が現在と同じ場合の日付区切りは `きょう`
- 日付が現在と異なる場合の日付区切りは 'Y年M月D日' 

上記でどうでしょうか？
諸々入れられればその方が分かりやすいとは思いますが、どのタイミングで実装するかはちょっと様子見つつですかね。

**Comment by hiroyuki** [comment]
ありがとうございます！
良いですね。
実装のタイミングは様子見でお願いしますー。
