### ISSUE TITLE
通知の中身が空 / 通知をタップした先の遷移ビューの設定

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#91]
![1912C0FF-64E4-4677-845E-BB8C17E9E49A](https://user-images.githubusercontent.com/109019/56456078-3665be00-63a2-11e9-8e9f-81a024b06460.png)

また、タップしても該当のビューに飛ばない

**Comment by inafact** [comment]
@hiroyuki 中身が空なのは原因調べてみますが、firebase / サーバー側の設定の関係もあるかもしれません。

また、プッシュ通知の仕様についていろいろ未確認だったかと..

> また、タップしても該当のビューに飛ばない

そもそもどんなタイプの通知があるのかを完全に把握できていないのですが、ひとまず、メッセージ（グループチャット、ユーザー間ダイレクトメッセージ、トピック（告知）に対するメッセージ）に関しては該当のthreadIdが付加されて飛んでくるようなので、タップして該当のスレッドを開くようなアクションを実装します。

それ以外、ポイントの受信や新規告知の投稿などに関しては、この辺りの通知・アクションは無いと思っていて良いでしょうか？

**Comment by hiroyuki** [comment]
@inafact それぞれの実装ボリュームを把握していないので、ベスト案は、バッチがついたものは、プッシュ通知でその該当ビューに飛ぶというのが良いです。
ただ、おっしゃるように、細かいところは決めきれてなかったとも思いますので、不自然ではなく。かつ、実装としてライトなところの落とし所があれば、逆に提案いただけると助かります。

**Comment by inafact** [comment]
ひとまず暫定として、通知データにメッセージのthread Id が付与されていた場合、該当のメッセージ詳細ビューを開くように実装します。
