### ISSUE TITLE
トピックの画像変更ができない

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#92]
トピックの画像変更をしても、変更されないです。

**Comment by inafact** [comment]
@hiroyuki 

（可能であれば発生機種も合わせてレポートいただけると幸いです..！）

こちら、変更がされないわけでなくて、アップロードした画像がプレビュー画面で切り替わるタイミングがうまくいってないのではないかという認識です。

同じ原因の症状として、複数回既存のトピックを編集して、１つ目の編集時に画像をアップロード・変更すると、２つ目のプレビューを表示した時、画像を指定してないものだと１つ目のものが表示されてしまうことがあるようです。
こちらに関しては修正対応進めます。

**Comment by hiroyuki** [comment]
iPhone xでもだめで、pixel 3でも、だめでした。

**Comment by inafact** [comment]
@hiroyuki 

> こちら、変更がされないわけでなくて、アップロードした画像がプレビュー画面で切り替わるタイミングがうまくいってないのではないかという認識です。
> 
> 同じ原因の症状として、複数回既存のトピックを編集して、１つ目の編集時に画像をアップロード・変更すると、２つ目のプレビューを表示した時、画像を指定してないものだと１つ目のものが表示されてしまうことがあるようです。
> こちらに関しては修正対応進めます。

に関しては

ios 1.1 build 1.0 / android 1.1 build 7

で修正済みです。
それ以外の要因というと、こちらでは症状を確認できていません。必要であれば再度オープンしてください。
