### ISSUE TITLE
トピックの削除機能

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#93]
デザインレビュー時に抜けていたのですが、トピックの削除ボタンをedit画面に追加していただきたいです。

**Comment by inafact** [comment]
@thirozumi 

一旦確認お願いします。

**Comment by thirozumi** [comment]
@hiroyuki @inafact 

こんな感じの動線でどうでしょうか。
https://sketch.cloud/s/V0ZVq/jgLvLbo/play

```
1. 右上のギアアイコン（自分が作成したトピックでしか出ません）をタップ
2. 編集（作成）ビュー下部の削除ボタンをタップ
3. 確認画面で「削除する」をタップ
4. 削除完了、一覧ビューで「トピックを削除しました」表記のスナックバーを出す
```

![Topic](https://user-images.githubusercontent.com/493379/56489975-8a95ad00-651e-11e9-8b93-8746ef79b166.png)

**Comment by hiroyuki** [comment]
@inafact @thirozumi ありがとうございます！よいとおもいます！

**Comment by inafact** [comment]
基本動作としては最初のリリース時に対応済みです。
@thirozumi  必要であれば確認お願いします。

**Comment by inafact** [comment]
対応済（クローズ漏れ？）かと思うので閉じまず。
何かあったら再オープンしてください
