### ISSUE TITLE
トピックの作成ボタンが押せない

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#94]
![311D173B-EC3F-40B3-B764-5E55D3A04CCC](https://user-images.githubusercontent.com/109019/56465877-cfe4ac80-6442-11e9-83bd-83a9cf3c5f33.jpeg)
これ以上下にスクロールできないとのこと。

端末：Androidバージョン8.1.0
機種：S2

**Comment by inafact** [comment]
@hiroyuki 

こちら最初のリリースの時点でエミュレーター上では修正確認してます。
実機で5インチ以下のものは手元で検証できないので、もし実機上で再現するようであれば再度オープンしてください
