### ISSUE TITLE
投稿画像のロードタイミングとパフォーマンス改善

### ISSUE THREAD

**Issue by thirozumi** [h4us/commons-people-app#96]
トピックやアイコンなど、投稿された画像を読み込むのに結構時間がかかっているので、備忘録的に起票させてください。

- バックグラウンドなりでロード処理のタイミングを設けるか、スプラッシュ画面でデフォルト or 直近にいたコミュニティの最新10件をプリロードしておくなどしておく？
- CDN を活用して高速化する？

<img src='https://user-images.githubusercontent.com/493379/56467290-07118880-6458-11e9-94b2-1f8ee4e5985f.png' width='375'>

**Comment by inafact** [comment]
@thirozumi 

いずれにしろパフォーマンスチューニングは必要だと思いますが、下記、現状で回答できるものに関しての回答と、実装的にボトルネックになっているのを把握している内容を共有しておきます。

> CDN を活用して高速化する？

現状配信元がS3なので、そこまで見込めないかと。
強いていえば画像のサイズを必要なものに分けて分類するなどでしょうか。こちらサーバー側実装と連携が必要になると思います。

> バックグラウンドなりでロード処理のタイミングを設けるか、スプラッシュ画面でデフォルト or 直近にいたコミュニティの最新10件をプリロードしておくなどしておく？

若干本筋からそれますが、現状、デザイン上の都合／実装上の都合で、APIのページングを使用できていない箇所とOSネィティブのリストビュー使用せず単に要素をforループで回して描画させている箇所があります。

前者はAPIから全てエントリを取得しているのでネットワーク的な遅延がボトルネック、後者は描画パフォーマンス的なボトルネック（ネイティブのリストビューを使用できると画面内に入っていない要素に関して遅延評価を勝手にやってくれる模様）で、まずはこの辺りの解決からになると思います。

前者に関しては順次移行中、後者も可能な限り使うよう実装を調整してますが、構成的に難しい箇所もあるので、どこかのタイミングでデザイン的な相談もさせてもらうかもしれません。

**Comment by hiroyuki** [comment]
@inafact こちらの件で、一点確認ですが、今UIの表示系と、画像のロード系は別のスレッド（非同期）にすることはできないのでしょうか？現状画像がロードされないとUIも表示されないようになっているように見えるのですが、この辺りはデバイスに依存するのでしょうか？

**Comment by inafact** [comment]
@hiroyuki 

すみません、正直な所ネイティブのフレームワークの細かい仕様については僕も把握していません..

> 今UIの表示系と、画像のロード系は別のスレッド（非同期）にすることはできないのでしょうか？

が、結論を先にいうと、できるはずです。
こちら、いくつか複合的な状況で、全部説明すると長くなりそうなので、適当に端折ります...。

今開発に利用しているフレームワークというのが JavaScript / TypeScript のコードベースからネィテイブアプリをビルドできるというものなの_（Cordovaも同様.. ただしこっちは描画を最終的にWebViewに任せるので、スレッドの管理などはWebView以下のものになるはずです。一長一短あるのではと思います..）_ですが、ビルド時に埋め込まれたJavaScriptのランタイムから直接ネイティブのUIフレームワークを操作する形になっており、これがNode.jsなどと同様、基本シングルスレッドです。

ネィティブのUIフレームワーク側で非同期の画像読み込みを行うことは可能なはずなので、ランタイム側から効率的にネイティブのUIフレームワークに処理を引き継ぐことができればこの辺り改善されるはずです。というのが、

>  後者は描画パフォーマンス的なボトルネック（ネイティブのリストビューを使用できると画面内に入っていない要素に関して遅延評価を勝手にやってくれる模様）で、まずはこの辺りの解決からになると思います。

端的に、今表示画像等の読み込みが終わってから表示されているように見える箇所は、どちらかというとビューの構成要素が複雑になっていて、JavaScript のランタイム上での構築処理重くなっている箇所です。

**Comment by inafact** [comment]
実例でいうと、

- コミュニティのトップ → 構成要素が複雑になっていてリストビューを利用できていない
- メッセージ詳細 → 構成要素が複雑になっていてリストビューを利用できていない / API のページング利用でリストビューへの移行を対応中
- メッセージスレッド検索・一覧 → API のページング利用でリストビューへ移行中。次のアップデートで差し替え予定

**Comment by inafact** [comment]
こちら施策的には #116 と同様のことになると思うのでマージします。
パフォーマンスチューニングという意味では必要箇所に応じて細かく切り出していたほうが良いかと。

merged #116
