### ISSUE TITLE
メッセージ板を開いたときに最新のメッセージが下に見切れている

### ISSUE THREAD

**Issue by hiroyuki** [h4us/commons-people-app#97]
最新のメッセージが表示されるようにしたい

**Comment by hiroyuki** [comment]
![EAEC938C-04E1-4C7D-B4D5-B21FFA7D01DF](https://user-images.githubusercontent.com/109019/56479691-a3d43480-64f1-11e9-92d8-30c3b5962ce7.png)

**Comment by inafact** [comment]
@hiroyuki 

こちらiOSのスクロールビューの挙動関連で同じ問題なので、 #24 にマージします

merged #24
